"""Deterministic, provenance-complete Primary Treatment Plan synthesis (TP-12).

The public seam is :class:`PrimaryPlanSynthesizer`. Model posterior states can
only select entries from an exact, versioned policy catalog. In particular,
neither medication identity nor dose is accepted from free text or generated by
an unconstrained model.
"""
from __future__ import annotations

import hashlib
import json
import math
from dataclasses import asdict, dataclass
from enum import Enum
from importlib.resources import files
from typing import Any, Mapping, Sequence

from .bn_evaluation import BnEvaluationBundle, BnModel, ModelEvaluation
from .observability import current_observability
from .safety_policy import (
    AssessedRecommendation,
    Disposition,
    SafetyOutcome,
    SafetyPolicyDecision,
)


SYNTHESIS_POLICY_ID = "schizophrenia-research-primary-plan"
SYNTHESIS_POLICY_VERSION = "1.0.0"


class RecommendationKind(str, Enum):
    TREATMENT_SETTING = "treatment-setting"
    PHARMACOTHERAPY = "pharmacotherapy"
    NEXT_APPOINTMENT = "next-appointment"


class EvidenceKind(str, Enum):
    SOURCE_FACT = "source-fact"
    MODEL_EVALUATION = "model-evaluation"
    POLICY_RULE = "policy-rule"


@dataclass(frozen=True)
class SourceFact:
    """Stable pointer to an authoritative fact consumed by a BN evaluation."""

    fact_id: str
    source_module: str
    resource_id: str
    schema_version: str
    content_hash: str
    path: str
    model: BnModel


@dataclass(frozen=True)
class EvidenceLink:
    kind: EvidenceKind
    reference: str
    detail: str


@dataclass(frozen=True)
class PlanRecommendation:
    recommendation_id: str
    kind: RecommendationKind
    value: Mapping[str, str]
    narrative: str
    evidence_links: tuple[EvidenceLink, ...]


@dataclass(frozen=True)
class PlanLimitation:
    code: str
    narrative: str
    evidence_links: tuple[EvidenceLink, ...] = ()


@dataclass(frozen=True)
class PrimaryTreatmentPlan:
    snapshot_id: str
    synthesis_policy_id: str
    synthesis_policy_version: str
    synthesis_policy_status: str
    treatment_setting: PlanRecommendation
    pharmacotherapy: PlanRecommendation
    next_appointment: PlanRecommendation
    alternatives: tuple[PlanRecommendation, ...]
    limitations: tuple[PlanLimitation, ...]

    @property
    def recommendations(self) -> tuple[PlanRecommendation, ...]:
        return (
            self.treatment_setting,
            self.pharmacotherapy,
            self.next_appointment,
            *self.alternatives,
        )

    def to_dict(self) -> dict[str, Any]:
        def convert(value: Any) -> Any:
            if isinstance(value, Enum):
                return value.value
            if isinstance(value, tuple):
                return [convert(item) for item in value]
            if isinstance(value, dict):
                return {key: convert(item) for key, item in sorted(value.items())}
            if hasattr(value, "__dataclass_fields__"):
                return convert(asdict(value))
            return value

        return convert(self)

    @property
    def semantic_hash(self) -> str:
        canonical = json.dumps(
            self.to_dict(), sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
        return "sha256:" + hashlib.sha256(canonical).hexdigest()


class SynthesisBlocked(ValueError):
    """The inputs cannot safely produce a complete Primary Plan."""


@dataclass(frozen=True)
class _SettingOption:
    candidate_id: str
    setting: str
    rule_id: str


@dataclass(frozen=True)
class _MedicationOption:
    candidate_id: str
    medication_code: str
    code_system: str
    dose: str
    route: str
    frequency: str
    rule_id: str


@dataclass(frozen=True)
class _AppointmentOption:
    setting: str
    interval: str
    rule_id: str


@dataclass(frozen=True)
class _SynthesisPolicy:
    policy_id: str
    version: str
    status: str
    safety_policy_id: str
    safety_policy_version: str
    settings: Mapping[str, _SettingOption]
    medications: Mapping[str, _MedicationOption]
    appointments: Mapping[str, _AppointmentOption]
    limitations: tuple[str, ...]


_DISPOSITION_RANK = {
    Disposition.PREFERRED: 0,
    Disposition.STANDARD: 1,
    Disposition.DEPRIORITIZED: 2,
    Disposition.CONDITIONAL: 3,
    Disposition.EXCLUDED: 4,
}


def _bundled_policy() -> Mapping[str, Any]:
    path = files("treatment_plan.policies").joinpath(
        "primary-plan-synthesis.schizophrenia-research.v1.json"
    )
    return json.loads(path.read_text(encoding="utf-8"))


def _nonempty(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field} must be a non-empty string")
    return value


def _parse_policy(raw: Mapping[str, Any]) -> _SynthesisPolicy:
    if raw.get("policyId") != SYNTHESIS_POLICY_ID or raw.get("version") != SYNTHESIS_POLICY_VERSION:
        raise ValueError("synthesis policy identity does not match the supported version")
    compatibility = raw.get("compatibleSafetyPolicy")
    if not isinstance(compatibility, Mapping):
        raise ValueError("compatibleSafetyPolicy is required")

    settings: dict[str, _SettingOption] = {}
    for item in raw.get("settings", ()):
        candidate_id = _nonempty(item.get("candidateId"), "setting candidateId")
        if candidate_id in settings:
            raise ValueError("setting candidateId values must be unique")
        settings[candidate_id] = _SettingOption(
            candidate_id,
            _nonempty(item.get("setting"), "setting"),
            _nonempty(item.get("ruleId"), "setting ruleId"),
        )

    medications: dict[str, _MedicationOption] = {}
    for item in raw.get("pharmacotherapies", ()):
        candidate_id = _nonempty(item.get("candidateId"), "pharmacotherapy candidateId")
        if candidate_id in medications:
            raise ValueError("pharmacotherapy candidateId values must be unique")
        medications[candidate_id] = _MedicationOption(
            candidate_id,
            _nonempty(item.get("medicationCode"), "medicationCode"),
            _nonempty(item.get("codeSystem"), "codeSystem"),
            _nonempty(item.get("dose"), "dose"),
            _nonempty(item.get("route"), "route"),
            _nonempty(item.get("frequency"), "frequency"),
            _nonempty(item.get("ruleId"), "pharmacotherapy ruleId"),
        )

    appointments: dict[str, _AppointmentOption] = {}
    for item in raw.get("appointments", ()):
        setting = _nonempty(item.get("setting"), "appointment setting")
        if setting in appointments:
            raise ValueError("appointment setting values must be unique")
        appointments[setting] = _AppointmentOption(
            setting,
            _nonempty(item.get("interval"), "appointment interval"),
            _nonempty(item.get("ruleId"), "appointment ruleId"),
        )

    limitations = tuple(
        _nonempty(value, "limitation") for value in raw.get("limitations", ())
    )
    if not settings or not medications or not appointments or not limitations:
        raise ValueError("synthesis policy requires settings, pharmacotherapies, appointments, and limitations")
    if {option.setting for option in settings.values()} - set(appointments):
        raise ValueError("every configured setting requires an appointment rule")
    return _SynthesisPolicy(
        SYNTHESIS_POLICY_ID,
        SYNTHESIS_POLICY_VERSION,
        _nonempty(raw.get("status"), "status"),
        _nonempty(compatibility.get("policyId"), "compatible safety policyId"),
        _nonempty(compatibility.get("version"), "compatible safety policy version"),
        settings,
        medications,
        appointments,
        limitations,
    )


class PrimaryPlanSynthesizer:
    """Synthesize a complete plan through one deterministic, pure interface."""

    def __init__(self, policy: Mapping[str, Any] | None = None):
        self._policy = _parse_policy(policy if policy is not None else _bundled_policy())

    def synthesize(
        self,
        bundle: BnEvaluationBundle,
        safety: SafetyPolicyDecision,
        source_facts: Sequence[SourceFact],
        *,
        timezone: str,
    ) -> PrimaryTreatmentPlan:
        observer = current_observability()
        try:
            result = self._synthesize(bundle, safety, source_facts, timezone=timezone)
        except Exception:
            observer.metric("tp_generation_total", labels={"kind": "primary-plan", "outcome": "failure", "policy_version": self._policy.version})
            raise
        observer.metric("tp_generation_total", labels={"kind": "primary-plan", "outcome": "success", "policy_version": self._policy.version})
        observer.metric("tp_version_info", labels={"kind": "synthesis-policy", "version": self._policy.version})
        return result

    def _synthesize(
        self,
        bundle: BnEvaluationBundle,
        safety: SafetyPolicyDecision,
        source_facts: Sequence[SourceFact],
        *,
        timezone: str,
    ) -> PrimaryTreatmentPlan:
        self._validate_inputs(bundle, safety, source_facts, timezone)
        setting_model = self._evaluation(bundle, BnModel.TREATMENT_SETTING)
        medication_model = self._evaluation(bundle, BnModel.PHARMACOTHERAPY)

        setting_ranked = self._rank_catalog(setting_model, self._policy.settings)
        medication_ranked, excluded = self._rank_medications(medication_model, safety)
        setting_state, setting_probability = setting_ranked[0]
        medication_state, medication_probability, medication_assessment = medication_ranked[0]
        setting_option = self._policy.settings[setting_state]
        medication_option = self._policy.medications[medication_state]
        appointment = self._policy.appointments[setting_option.setting]

        selected_setting = self._setting_recommendation(
            setting_option, setting_probability, setting_model, source_facts
        )
        selected_medication = self._medication_recommendation(
            medication_option,
            medication_probability,
            medication_model,
            medication_assessment,
            source_facts,
        )
        next_appointment = self._appointment_recommendation(
            appointment, setting_state, setting_probability, setting_model, source_facts, timezone
        )

        alternatives: list[PlanRecommendation] = []
        alternatives.extend(
            self._setting_recommendation(self._policy.settings[state], probability, setting_model, source_facts)
            for state, probability in setting_ranked[1:]
        )
        alternatives.extend(
            self._medication_recommendation(
                self._policy.medications[state], probability, medication_model, assessment,
                source_facts,
            )
            for state, probability, assessment in medication_ranked[1:]
        )

        policy_link = self._policy_link("policy-status")
        limitations = [
            PlanLimitation(f"policy-limitation-{index}", text, (policy_link,))
            for index, text in enumerate(self._policy.limitations, 1)
        ]
        for assessment in excluded:
            links = tuple(
                self._policy_link(rule_id, safety=True) for rule_id in assessment.trace_rule_ids
            ) or (self._policy_link("safety-exclusion", safety=True),)
            limitations.append(PlanLimitation(
                f"excluded-{assessment.recommendation.recommendation_id}",
                f"Candidate {assessment.recommendation.recommendation_id} is excluded by the safety policy.",
                links,
            ))
        for assessment in (item[2] for item in medication_ranked if item[2].disposition is Disposition.CONDITIONAL):
            links = tuple(self._policy_link(rule_id, safety=True) for rule_id in assessment.trace_rule_ids)
            limitations.append(PlanLimitation(
                f"conditional-{assessment.recommendation.recommendation_id}",
                f"Candidate {assessment.recommendation.recommendation_id} requires explicit clinical review.",
                links,
            ))

        return PrimaryTreatmentPlan(
            bundle.snapshot_id,
            self._policy.policy_id,
            self._policy.version,
            self._policy.status,
            selected_setting,
            selected_medication,
            next_appointment,
            tuple(alternatives),
            tuple(limitations),
        )

    def _validate_inputs(
        self,
        bundle: BnEvaluationBundle,
        safety: SafetyPolicyDecision,
        source_facts: Sequence[SourceFact],
        timezone: str,
    ) -> None:
        if not bundle.complete:
            raise SynthesisBlocked("a complete, finding-free BN evaluation bundle is required")
        if safety.policy_id != self._policy.safety_policy_id or safety.policy_version != self._policy.safety_policy_version:
            raise SynthesisBlocked("safety policy identity is incompatible with the synthesis policy")
        if safety.outcome is SafetyOutcome.EMERGENCY_ESCALATION:
            raise SynthesisBlocked("emergency escalation must use the explicit safety pathway")
        if not isinstance(timezone, str) or "/" not in timezone:
            raise ValueError("timezone must be an IANA-style area/location value")
        if len({fact.fact_id for fact in source_facts}) != len(source_facts):
            raise ValueError("source fact ids must be unique")
        for fact in source_facts:
            _nonempty(fact.fact_id, "source fact id")
            _nonempty(fact.source_module, "source module")
            _nonempty(fact.resource_id, "source resource id")
            _nonempty(fact.schema_version, "source schema version")
            if not isinstance(fact.content_hash, str) or not fact.content_hash.startswith("sha256:") or len(fact.content_hash) != 71:
                raise ValueError("source content hash must be a sha256 digest")
            _nonempty(fact.path, "source fact path")
            if not isinstance(fact.model, BnModel):
                raise ValueError("source fact model must be a BnModel")
        for model in (BnModel.TREATMENT_SETTING, BnModel.PHARMACOTHERAPY):
            if not any(fact.model is model for fact in source_facts):
                raise SynthesisBlocked(f"source fact provenance is required for {model.value}")

    @staticmethod
    def _evaluation(bundle: BnEvaluationBundle, model: BnModel) -> ModelEvaluation:
        matches = [item for item in bundle.evaluations if item.model is model]
        if len(matches) != 1:
            raise SynthesisBlocked(f"exactly one {model.value} evaluation is required")
        return matches[0]

    @staticmethod
    def _rank_catalog(
        evaluation: ModelEvaluation, catalog: Mapping[str, Any]
    ) -> list[tuple[str, float]]:
        unknown = sorted(state for state, _ in evaluation.posterior if state not in catalog)
        if unknown:
            raise SynthesisBlocked("model returned candidates outside the synthesis policy: " + ", ".join(unknown))
        return sorted(evaluation.posterior, key=lambda item: (-item[1], item[0]))

    def _rank_medications(
        self, evaluation: ModelEvaluation, safety: SafetyPolicyDecision
    ) -> tuple[list[tuple[str, float, AssessedRecommendation]], list[AssessedRecommendation]]:
        self._rank_catalog(evaluation, self._policy.medications)
        assessed = {item.recommendation.recommendation_id: item for item in safety.recommendations}
        missing = sorted(state for state, _ in evaluation.posterior if state not in assessed)
        if missing:
            raise SynthesisBlocked("pharmacotherapy candidates lack safety assessment: " + ", ".join(missing))
        eligible: list[tuple[str, float, AssessedRecommendation]] = []
        excluded: list[AssessedRecommendation] = []
        for state, probability in evaluation.posterior:
            item = assessed[state]
            if not math.isclose(item.recommendation.probability, probability, abs_tol=1e-12):
                raise SynthesisBlocked(f"safety probability differs from model posterior for {state}")
            if item.disposition is Disposition.EXCLUDED:
                excluded.append(item)
            else:
                eligible.append((state, probability, item))
        eligible.sort(key=lambda item: (_DISPOSITION_RANK[item[2].disposition], -item[1], item[0]))
        excluded.sort(key=lambda item: item.recommendation.recommendation_id)
        if not eligible:
            raise SynthesisBlocked("no pharmacotherapy candidate remains after safety policy")
        return eligible, excluded

    def _setting_recommendation(
        self,
        option: _SettingOption,
        probability: float,
        evaluation: ModelEvaluation,
        facts: Sequence[SourceFact],
    ) -> PlanRecommendation:
        links = self._base_links(evaluation, option.candidate_id, probability, option.rule_id, facts)
        narrative = (
            f"Recommend {option.setting} treatment setting; model posterior "
            f"for {option.candidate_id} is {probability:.6f}."
        )
        return PlanRecommendation(
            f"setting:{option.candidate_id}", RecommendationKind.TREATMENT_SETTING,
            {"setting": option.setting}, narrative, links,
        )

    def _medication_recommendation(
        self,
        option: _MedicationOption,
        probability: float,
        evaluation: ModelEvaluation,
        assessment: AssessedRecommendation,
        facts: Sequence[SourceFact],
    ) -> PlanRecommendation:
        links = list(self._base_links(
            evaluation, option.candidate_id, probability, option.rule_id, facts
        ))
        links.extend(self._policy_link(rule_id, safety=True) for rule_id in assessment.trace_rule_ids)
        if not assessment.trace_rule_ids:
            links.append(self._policy_link("no-safety-rule-matched", safety=True))
        narrative = (
            f"Recommend policy-catalog pharmacotherapy {option.medication_code} at "
            f"{option.dose}, {option.route}, {option.frequency}; model posterior is "
            f"{probability:.6f} and safety disposition is {assessment.disposition.value}."
        )
        return PlanRecommendation(
            f"pharmacotherapy:{option.candidate_id}", RecommendationKind.PHARMACOTHERAPY,
            {
                "medicationCode": option.medication_code,
                "codeSystem": option.code_system,
                "dose": option.dose,
                "route": option.route,
                "frequency": option.frequency,
            },
            narrative,
            tuple(links),
        )

    def _appointment_recommendation(
        self,
        option: _AppointmentOption,
        setting_state: str,
        probability: float,
        evaluation: ModelEvaluation,
        facts: Sequence[SourceFact],
        timezone: str,
    ) -> PlanRecommendation:
        links = self._base_links(evaluation, setting_state, probability, option.rule_id, facts)
        narrative = (
            f"Recommend the next appointment after {option.interval} in {timezone}, "
            f"using the configured follow-up rule for {option.setting}."
        )
        return PlanRecommendation(
            f"next-appointment:{option.setting}", RecommendationKind.NEXT_APPOINTMENT,
            {"interval": option.interval, "timezone": timezone}, narrative, links,
        )

    def _base_links(
        self,
        evaluation: ModelEvaluation,
        state: str,
        probability: float,
        rule_id: str,
        facts: Sequence[SourceFact],
    ) -> tuple[EvidenceLink, ...]:
        source_links = tuple(
            EvidenceLink(
                EvidenceKind.SOURCE_FACT,
                fact.fact_id,
                f"{fact.source_module}:{fact.resource_id}@{fact.schema_version}#{fact.content_hash}{fact.path}",
            )
            for fact in sorted(facts, key=lambda item: item.fact_id)
            if fact.model is evaluation.model
        )
        model_link = EvidenceLink(
            EvidenceKind.MODEL_EVALUATION,
            evaluation.evaluation_id,
            f"{evaluation.model.value}@{evaluation.model_version}#{evaluation.model_hash}; state={state}; probability={probability:.12f}",
        )
        return (*source_links, model_link, self._policy_link(rule_id))

    def _policy_link(self, rule_id: str, *, safety: bool = False) -> EvidenceLink:
        if safety:
            reference = f"{self._policy.safety_policy_id}@{self._policy.safety_policy_version}#{rule_id}"
            detail = "deterministic safety-policy rule provenance"
        else:
            reference = f"{self._policy.policy_id}@{self._policy.version}#{rule_id}"
            detail = "deterministic synthesis-policy rule provenance"
        return EvidenceLink(EvidenceKind.POLICY_RULE, reference, detail)



