"""Build diagnosis knowledge graph batch files directly from source analysis."""
import json, os

OUT = "E:\\diagnosis\\.understand-anything\\intermediate"
os.makedirs(OUT, exist_ok=True)

NODES = []
EDGES = []

def node(**kw):
    n = {"complexity": "moderate", "languageNotes": "", **kw}
    NODES.append(n)
    return n["id"]  # return id string for use in edge() calls

def edge(src, tgt, typ, w=0.5):
    EDGES.append({"source": src, "target": tgt, "type": typ, "weight": w})

# ── BATCH 1 ── Core wiring: __init__, __main__, app, api, deps ───────────────

b1 = {
  "nodes": [
    node(id="file:diagnosis/__init__.py", type="file", name="diagnosis/__init__.py",
         filePath="diagnosis/__init__.py", language="python",
         summary="Package entrypoint. Re-exports router, evaluate, get_criteria, meta_contract, check_readiness, and lazy get_app() so importing criteria alone never pulls in FastAPI.",
         tags=["package-init","public-api","lazy-imports","deep-module"], fileCategory="code"),
    node(id="file:diagnosis/__main__.py", type="file", name="diagnosis/__main__.py",
         filePath="diagnosis/__main__.py", language="python",
         summary="Standalone boot shim. Sets DIAGNOSIS_AUTH_BYPASS=1 before any submodule import, runs six self-checks (criteria, store, patient, readiness, config, HTTP), drops bypass, then uvicorn.run(diagnosis.app:app).",
         tags=["entrypoint","cli","self-check","uvicorn"], fileCategory="code"),
    node(id="file:diagnosis/app.py", type="file", name="diagnosis/app.py",
         filePath="diagnosis/app.py", language="python",
         summary="Standalone FastAPI app. Adds CORSMiddleware (origins from settings adapter), includes the composed router, serves /health (liveness) and /ready (readiness with 503 on failure).",
         tags=["fastapi","standalone-app","health","ready"], fileCategory="code"),
    node(id="file:diagnosis/api.py", type="file", name="diagnosis/api.py",
         filePath="diagnosis/api.py", language="python",
         summary="Composition root. Flattens three seam routers (page, dashboard, diagnosis_api) into one router preserving the literal-before-parameterized route order invariant. Back-compat re-exports store, Submission, RESULT_FIELDS, _dump_for_audit, _read_page, _http_selfcheck.",
         tags=["composition-root","api-router","seam-composition","back-compat"], fileCategory="code"),
    node(id="file:diagnosis/deps.py", type="file", name="diagnosis/deps.py",
         filePath="diagnosis/deps.py", language="python",
         summary="Shared wiring for all three route seams. Exports the process-wide DiagnosisStore singleton, require_psychiatrist, require_psychiatrist_or_admin, and require_csrf. Bypass shim (DIAGNOSIS_AUTH_BYPASS=1) is checked at import time.",
         tags=["shared-wiring","store-singleton","auth-dep","csrf-dep"], fileCategory="code"),
    node(id="module:diagnosis", type="module", name="diagnosis",
         filePath="",
         summary="Deep-module package: a tiny REST interface hiding the complete DSM-5-TR evaluation engine. Clinician-authoritative — the model never auto-decides.",
         tags=["deep-module","fastapi","clinical-decision-support"], complexity="moderate"),
    node(id="function:diagnosis/__init__.py:get_app", type="function",
         name="get_app", filePath="diagnosis/__init__.py",
         summary="Lazy FastAPI app accessor. Imports app only on call so criteria engine can be imported without triggering FastAPI load.",
         tags=["lazy-import","app-accessor"], complexity="simple"),
    node(id="function:diagnosis/__main__.py:main", type="function",
         name="main", filePath="diagnosis/__main__.py",
         summary="CLI entry function. Sets bypass, runs six self-checks, drops bypass, starts uvicorn.",
         tags=["cli-entry","self-check-runner"], complexity="simple"),
    node(id="endpoint:diagnosis/app.py:GET /health", type="endpoint",
         name="GET /health", filePath="diagnosis/app.py",
         summary="Liveness probe. Returns {ok: true, module: 'diagnosis'}.",
         tags=["liveness","probe","get-endpoint"], complexity="simple"),
    node(id="endpoint:diagnosis/app.py:GET /ready", type="endpoint",
         name="GET /ready", filePath="diagnosis/app.py",
         summary="Readiness probe. Calls check_readiness(); returns 200 with state or 503 when any check fails. Shape is stable; never leaks URLs or secrets.",
         tags=["readiness","probe","503","no-leak","get-endpoint"], complexity="simple"),
  ],
  "edges": [
    edge("file:diagnosis/__init__.py","file:diagnosis/api.py","imports",0.7),
    edge("file:diagnosis/__init__.py","file:diagnosis/criteria.py","imports",0.7),
    edge("file:diagnosis/__init__.py","file:diagnosis/readiness.py","imports",0.7),
    edge("file:diagnosis/__init__.py","module:diagnosis","defines_schema",0.8),
    edge("file:diagnosis/__main__.py","file:diagnosis/criteria.py","imports",0.7),
    edge("file:diagnosis/__main__.py","file:diagnosis/store.py","imports",0.7),
    edge("file:diagnosis/__main__.py","file:diagnosis/patient.py","imports",0.7),
    edge("file:diagnosis/__main__.py","file:diagnosis/readiness.py","imports",0.7),
    edge("file:diagnosis/__main__.py","file:diagnosis/config.py","imports",0.7),
    edge("file:diagnosis/__main__.py","file:diagnosis/api.py","imports",0.7),
    edge("file:diagnosis/__main__.py","file:diagnosis/app.py","imports",0.7),
    edge("file:diagnosis/app.py","file:diagnosis/api.py","imports",0.7),
    edge("file:diagnosis/app.py","file:diagnosis/config.py","imports",0.7),
    edge("file:diagnosis/app.py","file:diagnosis/readiness.py","imports",0.7),
    edge("file:diagnosis/app.py","file:diagnosis/readiness.py","calls",0.8),
    edge("file:diagnosis/app.py","endpoint:diagnosis/app.py:GET /health","contains",1.0),
    edge("file:diagnosis/app.py","endpoint:diagnosis/app.py:GET /ready","contains",1.0),
    edge("file:diagnosis/api.py","file:diagnosis/dashboard.py","imports",0.7),
    edge("file:diagnosis/api.py","file:diagnosis/diagnosis_api.py","imports",0.7),
    edge("file:diagnosis/api.py","file:diagnosis/page.py","imports",0.7),
    edge("file:diagnosis/api.py","file:diagnosis/deps.py","imports",0.7),
    edge("file:diagnosis/api.py","module:diagnosis","defines_schema",0.8),
    edge("file:diagnosis/deps.py","file:diagnosis/store.py","imports",0.7),
    edge("file:diagnosis/deps.py","file:diagnosis/auth.py","imports",0.7),
    edge("file:diagnosis/deps.py","file:diagnosis/csrf.py","imports",0.7),
    edge("file:diagnosis/__init__.py","function:diagnosis/__init__.py:get_app","contains",1.0),
    edge("file:diagnosis/__main__.py","function:diagnosis/__main__.py:main","contains",1.0),
  ]
}

# ── BATCH 2 ── Evaluation engine, config, patient identity ───────────────────

b2 = {
  "nodes": [
    node(id="file:diagnosis/criteria.py", type="file", name="diagnosis/criteria.py",
         filePath="diagnosis/criteria.py", language="python",
         summary="Pure-function DSM-5-TR evaluation engine. CRITERIA list holds 9 criterion dicts (A1-A6, B1, C1, D1). evaluate(checked_ids) -> Evaluation with no side effects. meta_contract() exposes the rule primitives the browser page consumes for optimistic display. Locked by test_unittest.TestCriteriaRules.",
         tags=["clinical-logic","pure-function","dsm-5-tr","criteria-engine"], fileCategory="code"),
    node(id="file:diagnosis/config.py", type="file", name="diagnosis/config.py",
         filePath="diagnosis/config.py", language="python",
         summary="Settings adapter: single source of truth for every integration knob (db_path, auth_url, patient_url, cors_origins, mock_auth, csrf_secret, module_base_path, host, port). Frozen Settings dataclass read once at import. The only place to add a new env knob.",
         tags=["settings","config-adapter","frozen-dataclass","env-knobs"], fileCategory="code"),
    node(id="file:diagnosis/patient.py", type="file", name="diagnosis/patient.py",
         filePath="diagnosis/patient.py", language="python",
         summary="Patient identity adapter. Aligns free-text {code} path param with canonical INSIGHT patient.id via internal REST lookup (GET /api/patients/lookup). Opt-in via DIAGNOSIS_PATIENT_LOOKUP=1; default disabled preserves prior diagnosis-local identity for self-check and offline tests.",
         tags=["patient-identity","adapter","canonical-id","opt-in"], fileCategory="code"),
    node(id="file:diagnosis/readiness.py", type="file", name="diagnosis/readiness.py",
         filePath="diagnosis/readiness.py", language="python",
         summary="Module-local readiness probe. Pure check_readiness() aggregates DB (SELECT 1), Auth (configured + not bypassed), and Patient (configured when enabled) checks. Never calls live services or leaks URLs. Route in app.py maps ok to 200/503.",
         tags=["readiness","probe","no-leak","module-local"], fileCategory="code"),
    node(id="class:diagnosis/criteria.py:Evaluation", type="class",
         name="Evaluation", filePath="diagnosis/criteria.py",
         summary="Dataclass holding evaluation result: met (bool), checked_ids, a_count, core_count, failures list, reason string. No decision field — clinician authority is a tested contract at the REST layer.",
         tags=["dataclass","evaluation-result","clinical-logic"], complexity="simple"),
    node(id="class:diagnosis/config.py:Settings", type="class",
         name="Settings", filePath="diagnosis/config.py",
         summary="Frozen dataclass snapshot of every integration knob. Properties: module_id (derived from module_base_path), launch_href (derived from module_id).",
         tags=["frozen-dataclass","settings","config"], complexity="simple"),
    node(id="class:diagnosis/patient.py:Patient", type="class",
         name="Patient", filePath="diagnosis/patient.py",
         summary="Frozen dataclass for canonical patient identity consumed by store.put. Fields: id (INSIGHT registry pk), patient_code (free-text), display_name.",
         tags=["patient-identity","frozen-dataclass"], complexity="simple"),
    node(id="function:diagnosis/criteria.py:evaluate", type="function",
         name="evaluate", filePath="diagnosis/criteria.py",
         summary="Pure function: given checked criterion ids returns an Evaluation. Rules: >=2 A symptoms, >=1 from core triad (A1-A3), duration (A6) required, guards B/C/D must be checked. No side effects.",
         tags=["pure-function","criteria-evaluation"], complexity="moderate"),
    node(id="function:diagnosis/criteria.py:get_criteria", type="function",
         name="get_criteria", filePath="diagnosis/criteria.py",
         summary="Returns a copy of the CRITERIA list for the UI criteria tree. Caller must not mutate.",
         tags=["criteria-tree","ui-bootstrap"], complexity="simple"),
    node(id="function:diagnosis/criteria.py:meta_contract", type="function",
         name="meta_contract", filePath="diagnosis/criteria.py",
         summary="Returns the rule contract dict the browser page uses for optimistic display (symptom_ids, core_ids, duration_id, guard_ids, thresholds). Single source of truth — server rules drive the UI, not JS mirroring.",
         tags=["rule-contract","ui-optimistic-display","single-source-of-truth"], complexity="simple"),
    node(id="function:diagnosis/criteria.py:_demo", type="function",
         name="_demo", filePath="diagnosis/criteria.py",
         summary="Boot-time self-check shim: runs test_unittest.TestCriteriaRules via stdlib unittest and exits non-zero on failure.",
         tags=["self-check","boot-fail-fast"], complexity="simple"),
    node(id="function:diagnosis/config.py:_env_truthy", type="function",
         name="_env_truthy", filePath="diagnosis/config.py",
         summary="Returns True when env var == '1', False otherwise.",
         tags=["env-helper"], complexity="simple"),
    node(id="function:diagnosis/config.py:_env_list", type="function",
         name="_env_list", filePath="diagnosis/config.py",
         summary="Parses comma-separated env list; '*' returns default list verbatim.",
         tags=["env-helper","comma-list"], complexity="simple"),
    node(id="function:diagnosis/config.py:_load", type="function",
         name="_load", filePath="diagnosis/config.py",
         summary="Builds a Settings instance from env vars with prior hard-coded defaults. Pure, never raises on missing values.",
         tags=["settings-loader","env-adapter"], complexity="simple"),
    node(id="function:diagnosis/config.py:_config_selfcheck", type="function",
         name="_config_selfcheck", filePath="diagnosis/config.py",
         summary="Self-verify the settings adapter: blank env returns prior defaults, custom env is honoured, Settings is frozen.",
         tags=["self-check","settings"], complexity="simple"),
    node(id="function:diagnosis/patient.py:resolve_patient", type="function",
         name="resolve_patient", filePath="diagnosis/patient.py",
         summary="Resolves free-text code to Patient. When DIAGNOSIS_PATIENT_LOOKUP!=1 (default): returns self-consistent Patient(id=code). When enabled: calls registry, maps 404/transport/id-missing to 422.",
         tags=["patient-resolution","registry-lookup","422-map"], complexity="moderate"),
    node(id="function:diagnosis/patient.py:reset_patient_for_tests", type="function",
         name="reset_patient_for_tests", filePath="diagnosis/patient.py",
         summary="Test-only hook: rebinds PATIENT_BASE_URL module global for fake-registry tests.",
         tags=["test-hook","fake-registry"], complexity="simple"),
    node(id="function:diagnosis/patient.py:_patient_selfcheck", type="function",
         name="_patient_selfcheck", filePath="diagnosis/patient.py",
         summary="Self-verify patient adapter: empty code 400, lookup-disabled fallback, _build_patient closed on missing id.",
         tags=["self-check","patient-adapter"], complexity="simple"),
    node(id="function:diagnosis/readiness.py:check_readiness", type="function",
         name="check_readiness", filePath="diagnosis/readiness.py",
         summary="Pure function returning {ok, module, checks: {db, auth, patient}}. Never raises, never calls live services.",
         tags=["readiness","pure-function"], complexity="simple"),
    node(id="function:diagnosis/readiness.py:_check_db", type="function",
         name="_check_db", filePath="diagnosis/readiness.py",
         summary="Probes DiagnosisStore with SELECT 1. Catches all SQLite faults and returns ok=False without leaking the error.",
         tags=["db-check","select-1"], complexity="simple"),
    node(id="function:diagnosis/readiness.py:_check_auth", type="function",
         name="_check_auth", filePath="diagnosis/readiness.py",
         summary="Checks AUTH_BASE_URL is non-empty and bypass shim is off. Never calls the auth service.",
         tags=["auth-config-check","no-service-call"], complexity="simple"),
    node(id="function:diagnosis/readiness.py:_check_patient", type="function",
         name="_check_patient", filePath="diagnosis/readiness.py",
         summary="When DIAGNOSIS_PATIENT_LOOKUP=1: checks PATIENT_BASE_URL non-empty. Otherwise returns {ok:true, enabled:False, configured:true} (skipped is healthy).",
         tags=["patient-config-check","opt-in"], complexity="simple"),
    node(id="function:diagnosis/readiness.py:_readiness_selfcheck", type="function",
         name="_readiness_selfcheck", filePath="diagnosis/readiness.py",
         summary="Self-verify readiness probe: default env=ready, bypass=on=fails-readiness, patient-enrolled+URL-set=ready, patient-enrolled+blank-URL=fails, DB-fault=False-without-raising.",
         tags=["self-check","readiness"], complexity="moderate"),
  ],
  "edges": [
    edge("file:diagnosis/criteria.py","class:diagnosis/criteria.py:Evaluation","contains",1.0),
    edge("file:diagnosis/criteria.py","function:diagnosis/criteria.py:evaluate","contains",1.0),
    edge("file:diagnosis/criteria.py","function:diagnosis/criteria.py:get_criteria","contains",1.0),
    edge("file:diagnosis/criteria.py","function:diagnosis/criteria.py:meta_contract","contains",1.0),
    edge("file:diagnosis/criteria.py","function:diagnosis/criteria.py:_demo","contains",1.0),
    edge("file:diagnosis/config.py","class:diagnosis/config.py:Settings","contains",1.0),
    edge("file:diagnosis/config.py","function:diagnosis/config.py:_env_truthy","contains",1.0),
    edge("file:diagnosis/config.py","function:diagnosis/config.py:_env_list","contains",1.0),
    edge("file:diagnosis/config.py","function:diagnosis/config.py:_load","contains",1.0),
    edge("file:diagnosis/config.py","function:diagnosis/config.py:_config_selfcheck","contains",1.0),
    edge("file:diagnosis/patient.py","class:diagnosis/patient.py:Patient","contains",1.0),
    edge("file:diagnosis/patient.py","function:diagnosis/patient.py:resolve_patient","contains",1.0),
    edge("file:diagnosis/patient.py","function:diagnosis/patient.py:reset_patient_for_tests","contains",1.0),
    edge("file:diagnosis/patient.py","function:diagnosis/patient.py:_patient_selfcheck","contains",1.0),
    edge("file:diagnosis/readiness.py","function:diagnosis/readiness.py:check_readiness","contains",1.0),
    edge("file:diagnosis/readiness.py","function:diagnosis/readiness.py:_check_db","contains",1.0),
    edge("file:diagnosis/readiness.py","function:diagnosis/readiness.py:_check_auth","contains",1.0),
    edge("file:diagnosis/readiness.py","function:diagnosis/readiness.py:_check_patient","contains",1.0),
    edge("file:diagnosis/readiness.py","function:diagnosis/readiness.py:_readiness_selfcheck","contains",1.0),
    edge("file:diagnosis/deps.py","file:diagnosis/criteria.py","imports",0.7),
    edge("file:diagnosis/deps.py","file:diagnosis/patient.py","imports",0.7),
    edge("file:diagnosis/deps.py","file:diagnosis/config.py","imports",0.7),
    edge("file:diagnosis/readiness.py","file:diagnosis/deps.py","imports",0.7),
    edge("file:diagnosis/readiness.py","file:diagnosis/store.py","imports",0.7),
    edge("file:diagnosis/patient.py","file:diagnosis/config.py","imports",0.7),
    edge("file:diagnosis/patient.py","file:diagnosis/auth.py","imports",0.7),
    edge("file:diagnosis/config.py","file:diagnosis/csrf.py","imports",0.7),
    edge("file:diagnosis/criteria.py","file:diagnosis/__init__.py","exports",0.8),
    edge("file:diagnosis/readiness.py","file:diagnosis/__init__.py","exports",0.8),
  ]
}

# ── BATCH 3 ── Auth, CSRF, store ─────────────────────────────────────────────

b3 = {
  "nodes": [
    node(id="file:diagnosis/auth.py", type="file", name="diagnosis/auth.py",
         filePath="diagnosis/auth.py", language="python",
         summary="Auth adapter delegating trust to the central Insight auth service. Calls GET {AUTH_BASE_URL}/api/auth/session with the Cookie header and reads the JSON response (authenticated, user_id, roles, session_id). Never decodes JWTs or reads the auth DB.",
         tags=["auth-delegation","session","role-enforcement","insight-service"], fileCategory="code"),
    node(id="file:diagnosis/csrf.py", type="file", name="diagnosis/csrf.py",
         filePath="diagnosis/csrf.py", language="python",
         summary="Signed double-submit CSRF token (HMAC-SHA256). mint() creates a fresh token set as cookie + JSON body. require_csrf FastAPI dependency fails closed on any cookie/header mismatch or invalid signature. Pinned secret via DIAGNOSIS_CSRF_SECRET; per-process random fallback.",
         tags=["csrf","hmac-sha256","double-submit","owasp"], fileCategory="code"),
    node(id="file:diagnosis/store.py", type="file", name="diagnosis/store.py",
         filePath="diagnosis/store.py", language="python",
         summary="SQLite-backed repository adapter. DiagnosisStore wraps sessions (code PK, patient_id, checked JSON, decision) and audit (id, code, snapshot JSON, created_at) tables. WAL journal, thread-safe via process lock. Covers init, get, put, audit_snapshot, list_audits, reset.",
         tags=["persistence","sqlite","repository","wal-journal"], fileCategory="code"),
    node(id="class:diagnosis/auth.py:Session", type="class",
         name="Session", filePath="diagnosis/auth.py",
         summary="Frozen dataclass: user_id, roles (frozenset), session_id. Built from the auth service JSON response. has_any() checks role membership.",
         tags=["session","frozen-dataclass","role"], complexity="simple"),
    node(id="class:diagnosis/auth.py:_AuthUnavailable", type="class",
         name="_AuthUnavailable", filePath="diagnosis/auth.py",
         summary="Exception raised on auth service transport or parse failure. Route maps to 401 without leaking infra details.",
         tags=["auth-exception","transport-error"], complexity="simple"),
    node(id="class:diagnosis/store.py:DiagnosisStore", type="class",
         name="DiagnosisStore", filePath="diagnosis/store.py",
         summary="SQLite repository. Methods: init, exists, get, put, audit_snapshot, list_audits, reset. Thread-safe via threading.Lock. Lazy connection with WAL journal.",
         tags=["persistence","sqlite","thread-safe"], complexity="moderate"),
    node(id="function:diagnosis/auth.py:require_role", type="function",
         name="require_role", filePath="diagnosis/auth.py",
         summary="FastAPI dependency factory. Returns a dependency that enforces role membership. Reads cookie, calls auth service, returns Session or raises 401/403.",
         tags=["fastapi-dependency","role-enforcement"], complexity="moderate"),
    node(id="function:diagnosis/auth.py:reset_auth_for_tests", type="function",
         name="reset_auth_for_tests", filePath="diagnosis/auth.py",
         summary="Test-only hook: rebinds AUTH_BASE_URL module global for fake auth server tests.",
         tags=["test-hook","fake-auth"], complexity="simple"),
    node(id="function:diagnosis/csrf.py:mint", type="function",
         name="mint", filePath="diagnosis/csrf.py",
         summary="Creates a fresh signed CSRF token: 32 random hex bytes signed with HMAC-SHA256. Returns token string.",
         tags=["csrf-token","mint"], complexity="simple"),
    node(id="function:diagnosis/csrf.py:set_cookie", type="function",
         name="set_cookie", filePath="diagnosis/csrf.py",
         summary="Stamps the csrf cookie on a FastAPI response. HttpOnly=False so JS can read it; Secure flag from settings.",
         tags=["csrf","cookie"], complexity="simple"),
    node(id="function:diagnosis/csrf.py:require_csrf", type="function",
         name="require_csrf", filePath="diagnosis/csrf.py",
         summary="FastAPI dependency. Fails closed (403) if cookie/header missing, mismatched, or invalid HMAC. Bypassed when DIAGNOSIS_AUTH_BYPASS=1.",
         tags=["csrf-dependency","fastapi-dependency"], complexity="simple"),
    node(id="function:diagnosis/csrf.py:reset_secret_for_tests", type="function",
         name="reset_secret_for_tests", filePath="diagnosis/csrf.py",
         summary="Test-only hook: pins the CSRF secret so tests can mint predictable tokens. Pass None to reset to fresh random.",
         tags=["test-hook","csrf-secret"], complexity="simple"),
    node(id="function:diagnosis/store.py:_resolve_path", type="function",
         name="_resolve_path", filePath="diagnosis/store.py",
         summary="Resolves the SQLite DB path. Honours DIAGNOSIS_DB_PATH env var at call time (not import time) so mid-process flips work.",
         tags=["db-path","env-resolve"], complexity="simple"),
    node(id="function:diagnosis/store.py:_store_selfcheck", type="function",
         name="_store_selfcheck", filePath="diagnosis/store.py",
         summary="Self-verify persistence adapter end-to-end with a temp DB: init-once, timestamps monotonic, put+get round-trip, bypass decision, audit snapshot recorded and durable across store restarts.",
         tags=["self-check","persistence"], complexity="moderate"),
  ],
  "edges": [
    edge("file:diagnosis/auth.py","class:diagnosis/auth.py:Session","contains",1.0),
    edge("file:diagnosis/auth.py","class:diagnosis/auth.py:_AuthUnavailable","contains",1.0),
    edge("file:diagnosis/auth.py","function:diagnosis/auth.py:require_role","contains",1.0),
    edge("file:diagnosis/auth.py","function:diagnosis/auth.py:reset_auth_for_tests","contains",1.0),
    edge("file:diagnosis/csrf.py","function:diagnosis/csrf.py:mint","contains",1.0),
    edge("file:diagnosis/csrf.py","function:diagnosis/csrf.py:set_cookie","contains",1.0),
    edge("file:diagnosis/csrf.py","function:diagnosis/csrf.py:require_csrf","contains",1.0),
    edge("file:diagnosis/csrf.py","function:diagnosis/csrf.py:reset_secret_for_tests","contains",1.0),
    edge("file:diagnosis/store.py","class:diagnosis/store.py:DiagnosisStore","contains",1.0),
    edge("file:diagnosis/store.py","function:diagnosis/store.py:_resolve_path","contains",1.0),
    edge("file:diagnosis/store.py","function:diagnosis/store.py:_store_selfcheck","contains",1.0),
    edge("file:diagnosis/auth.py","file:diagnosis/config.py","imports",0.7),
    edge("file:diagnosis/csrf.py","file:diagnosis/config.py","imports",0.7),
    edge("file:diagnosis/store.py","file:diagnosis/config.py","imports",0.7),
    edge("file:diagnosis/deps.py","file:diagnosis/auth.py","imports",0.7),
    edge("file:diagnosis/deps.py","file:diagnosis/csrf.py","imports",0.7),
    edge("file:diagnosis/store.py","file:diagnosis/deps.py","imports",0.7),
  ]
}

# ── BATCH 4 ── Route seams: page, dashboard, diagnosis_api ───────────────────

b4 = {
  "nodes": [
    node(id="file:diagnosis/page.py", type="file", name="diagnosis/page.py",
         filePath="diagnosis/page.py", language="python",
         summary="Browser page seam. GET / serves static/index.html and stamps a fresh signed CSRF token into <meta name='csrf-token'> + the csrf cookie. Auth-gated (psychiatrist or admin). Under bypass shim the injection is skipped for byte-clean test asserts.",
         tags=["browser-page","spa","csrf-stamp","auth-gated"], fileCategory="code"),
    node(id="file:diagnosis/dashboard.py", type="file", name="diagnosis/dashboard.py",
         filePath="diagnosis/dashboard.py", language="python",
         summary="Dashboard discovery seam. Serves GET /diagnosis/_meta (criteria tree + meta_contract), GET /diagnosis/_csrf (mint token), GET /internal/dashboard/module-routes/{moduleId} (launch descriptor for the Insight Dashboard), and GET /internal/diagnosis/audit/{code} (audit trail). Read-only, auth-gated.",
         tags=["dashboard-discovery","module-routes","audit","discovery-seam"], fileCategory="code"),
    node(id="file:diagnosis/diagnosis_api.py", type="file", name="diagnosis/diagnosis_api.py",
         filePath="diagnosis/diagnosis_api.py", language="python",
         summary="Protected per-patient REST seam. POST /diagnosis/{code}/init (create session), GET /diagnosis/{code} (get session + evaluation), PUT /diagnosis/{code} (persist checked + decision, call audit hook). Writes require psychiatrist + CSRF; reads require psychiatrist or admin.",
         tags=["rest-seam","diagnosis-api","write-protected","per-patient"], fileCategory="code"),
    node(id="endpoint:diagnosis/dashboard.py:GET /diagnosis/_meta", type="endpoint",
         name="GET /diagnosis/_meta", filePath="diagnosis/dashboard.py",
         summary="Returns {criteria, rules}. criteria is the DSM-5-TR tree; rules is the meta_contract driving the UI optimistic display. No patient data.",
         tags=["get-endpoint","criteria-tree","rules-contract"], complexity="simple"),
    node(id="endpoint:diagnosis/dashboard.py:GET /diagnosis/_csrf", type="endpoint",
         name="GET /diagnosis/_csrf", filePath="diagnosis/dashboard.py",
         summary="Mints a signed CSRF token, sets the csrf cookie, returns {token}. Read-only.",
         tags=["get-endpoint","csrf","token-mint"], complexity="simple"),
    node(id="endpoint:diagnosis/dashboard.py:GET /internal/dashboard/module-routes/{moduleId}", type="endpoint",
         name="GET /internal/dashboard/module-routes/{moduleId}", filePath="diagnosis/dashboard.py",
         summary="Dashboard module-route discovery. Returns {moduleId, title, description, launch: {href}, routes: {self, csrf, session}} for moduleId==diagnosis, 404 otherwise.",
         tags=["get-endpoint","dashboard-discovery","module-routes"], complexity="simple"),
    node(id="endpoint:diagnosis/dashboard.py:GET /internal/diagnosis/audit/{code}", type="endpoint",
         name="GET /internal/diagnosis/audit/{code}", filePath="diagnosis/dashboard.py",
         summary="Audit-log seam. Returns {code, snapshots: [...]} with the chronological persisted audit trail. Unknown code returns empty snapshots list, not 404.",
         tags=["get-endpoint","audit","read-only"], complexity="simple"),
    node(id="endpoint:diagnosis/diagnosis_api.py:POST /diagnosis/{code}/init", type="endpoint",
         name="POST /diagnosis/{code}/init", filePath="diagnosis/diagnosis_api.py",
         summary="Create an empty session for a patient code. Resolves patient identity (canonical id), calls store.init, returns {created, patient_id}. CSRF + psychiatrist required.",
         tags=["post-endpoint","session-init","csrf-gated","psychiatrist-required"], complexity="simple"),
    node(id="endpoint:diagnosis/diagnosis_api.py:GET /diagnosis/{code}", type="endpoint",
         name="GET /diagnosis/{code}", filePath="diagnosis/diagnosis_api.py",
         summary="Return session state + live evaluation for a patient code. 404 if never seen. No patient data mutation.",
         tags=["get-endpoint","session-get","evaluation"], complexity="simple"),
    node(id="endpoint:diagnosis/diagnosis_api.py:PUT /diagnosis/{code}", type="endpoint",
         name="PUT /diagnosis/{code}", filePath="diagnosis/diagnosis_api.py",
         summary="Persist checked criteria ids + clinician decision ('confirmed' or 'definite'). Returns updated session + evaluation. Calls _dump_for_audit on every PUT. CSRF + psychiatrist required.",
         tags=["put-endpoint","session-put","csrf-gated","psychiatrist-required","audit-hook"], complexity="simple"),
    node(id="function:diagnosis/page.py:_read_page", type="function",
         name="_read_page", filePath="diagnosis/page.py",
         summary="Reads static/index.html from disk once per request. No build step.",
         tags=["file-read","static-html"], complexity="simple"),
    node(id="function:diagnosis/dashboard.py:_dump_for_audit", type="function",
         name="_dump_for_audit", filePath="diagnosis/dashboard.py",
         summary="Calls store.audit_snapshot and returns the JSON snapshot string. Called by put_session on every decision-bearing PUT so the local audit table accumulates without waiting for the Logs module.",
         tags=["audit-hook","snapshot"], complexity="simple"),
    node(id="class:diagnosis/diagnosis_api.py:Submission", type="class",
         name="Submission", filePath="diagnosis/diagnosis_api.py",
         summary="Pydantic model for PUT body: {checked: list[str], decision: 'confirmed'|'definite'|null}.",
         tags=["pydantic","request-body"], complexity="simple"),
  ],
  "edges": [
    edge("file:diagnosis/page.py","function:diagnosis/page.py:_read_page","contains",1.0),
    edge("file:diagnosis/page.py","endpoint:diagnosis/dashboard.py:GET /diagnosis/_meta","contains",1.0),
    edge("file:diagnosis/dashboard.py","endpoint:diagnosis/dashboard.py:GET /diagnosis/_meta","contains",1.0),
    edge("file:diagnosis/dashboard.py","endpoint:diagnosis/dashboard.py:GET /diagnosis/_csrf","contains",1.0),
    edge("file:diagnosis/dashboard.py","endpoint:diagnosis/dashboard.py:GET /internal/dashboard/module-routes/{moduleId}","contains",1.0),
    edge("file:diagnosis/dashboard.py","endpoint:diagnosis/dashboard.py:GET /internal/diagnosis/audit/{code}","contains",1.0),
    edge("file:diagnosis/dashboard.py","function:diagnosis/dashboard.py:_dump_for_audit","contains",1.0),
    edge("file:diagnosis/diagnosis_api.py","class:diagnosis/diagnosis_api.py:Submission","contains",1.0),
    edge("file:diagnosis/diagnosis_api.py","endpoint:diagnosis/diagnosis_api.py:POST /diagnosis/{code}/init","contains",1.0),
    edge("file:diagnosis/diagnosis_api.py","endpoint:diagnosis/diagnosis_api.py:GET /diagnosis/{code}","contains",1.0),
    edge("file:diagnosis/diagnosis_api.py","endpoint:diagnosis/diagnosis_api.py:PUT /diagnosis/{code}","contains",1.0),
    edge("file:diagnosis/page.py","file:diagnosis/auth.py","imports",0.7),
    edge("file:diagnosis/page.py","file:diagnosis/csrf.py","imports",0.7),
    edge("file:diagnosis/page.py","file:diagnosis/deps.py","imports",0.7),
    edge("file:diagnosis/dashboard.py","file:diagnosis/auth.py","imports",0.7),
    edge("file:diagnosis/dashboard.py","file:diagnosis/csrf.py","imports",0.7),
    edge("file:diagnosis/dashboard.py","file:diagnosis/criteria.py","imports",0.7),
    edge("file:diagnosis/dashboard.py","file:diagnosis/deps.py","imports",0.7),
    edge("file:diagnosis/dashboard.py","file:diagnosis/config.py","imports",0.7),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/auth.py","imports",0.7),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/criteria.py","imports",0.7),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/dashboard.py","imports",0.7),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/deps.py","imports",0.7),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/patient.py","imports",0.7),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/store.py","imports",0.7),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/criteria.py","calls",0.8),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/dashboard.py","calls",0.8),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/deps.py","calls",0.8),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/patient.py","calls",0.8),
    edge("file:diagnosis/diagnosis_api.py","file:diagnosis/store.py","calls",0.8),
    edge("file:diagnosis/page.py","file:diagnosis/static/index.html","reads_from",0.5),
  ]
}

# ── BATCH 5 ── Tests, docs, config, HTML, requirements ───────────────────────

b5 = {
  "nodes": [
    node(id="file:test_unittest.py", type="file", name="test_unittest.py",
         filePath="test_unittest.py", language="python",
         summary="Unittest suite locking clinical contracts: TestCriteriaRules (pure rule engine), TestRestContract (route/persistence contract), TestAuditSeam (audit hook on every PUT), TestClinicianAuthority (model-never-auto-decides invariant), TestAuthRejection, TestCSRF, TestPersistence, TestPatientIdentity.",
         tags=["unittest","clinical-contracts","criteria-rules","audit","authority-invariant"], fileCategory="code"),
    node(id="file:test_auth.py", type="file", name="test_auth.py",
         filePath="test_auth.py", language="python",
         summary="Role-enforcement tests. In-process fake HTTP server exercising all protected paths with no-cookie, unauthenticated, nurse-role, psychiatrist-role, and admin-role requests. No external framework — stdlib unittest + threading HTTP server.",
         tags=["auth-tests","role-enforcement","fake-http-server","ponytail-harness"], fileCategory="code"),
    node(id="file:test_config.py", type="file", name="test_config.py",
         filePath="test_config.py", language="python",
         summary="Settings adapter tests: blank env returns prior defaults, custom env is honoured, Settings is frozen, module_id derives from mount prefix, CORS parses comma list, mock_auth and patient_lookup are truthy gates, host/port override.",
         tags=["config-tests","settings-adapter","env-snapshot"], fileCategory="code"),
    node(id="file:test_csrf.py", type="file", name="test_csrf.py",
         filePath="test_csrf.py", language="python",
         summary="CSRF tests for write routes. Covers missing header, missing cookie, mismatch, bad signature, valid token allows write, token route sets cookie, HTML page carries meta tag, bypass env skips CSRF.",
         tags=["csrf-tests","double-submit","fake-http-server"], fileCategory="code"),
    node(id="file:test_discovery.py", type="file", name="test_discovery.py",
         filePath="test_discovery.py", language="python",
         summary="Dashboard module-route discovery tests: descriptor shape, admin can read, unknown moduleId 404, nurse role 403, no cookie 401.",
         tags=["discovery-tests","dashboard","module-routes"], fileCategory="code"),
    node(id="file:test_embed.py", type="file", name="test_embed.py",
         filePath="test_embed.py", language="python",
         summary="Embeddable module UI tests: page is standalone shell, exposes createDiagnosisModule, contract takes root+apiBaseUrl, drops dashboard placeholder, no standalone topbar, embedded flag skips chrome, mount/unmount handle, CSRF meta tag still read, route layer unchanged, bypass serve byte-clean.",
         tags=["embed-tests","ui-contract","createDiagnosisModule"], fileCategory="code"),
    node(id="file:test_patient.py", type="file", name="test_patient.py",
         filePath="test_patient.py", language="python",
         summary="Patient identity adapter tests: init/put bind canonical patient id, unknown code 422, registry 404 maps 422, empty code 400, missing canonical id 422, bad JSON 422, registry 500 422, registry down 422, lookup disabled falls back to free-text.",
         tags=["patient-tests","identity-adapter","registry-mock"], fileCategory="code"),
    node(id="file:test_readiness.py", type="file", name="test_readiness.py",
         filePath="test_readiness.py", language="python",
         summary="Readiness probe tests: default env is ready, bypass shim fails readiness, auth URL blank fails, patient lookup enabled+URL-set ready, patient lookup enabled+blank-URL fails, DB fault is False without raising, HTTP 200/503, response never leaks URLs.",
         tags=["readiness-tests","probe","no-leak"], fileCategory="code"),
    node(id="file:test_routes.py", type="file", name="test_routes.py",
         filePath="test_routes.py", language="python",
         summary="Route-seam split tests: page seam owns only browser page, dashboard seam owns only discovery routes, diagnosis seam owns only per-patient REST, composed router has all paths, literal routes precede parameterized, audit seam is in dashboard only, discovery moduleId constant, back-compat re-exports, each seam shares one store and policy.",
         tags=["route-tests","seam-split","route-invariants"], fileCategory="code"),
    node(id="file:diagnosis/static/index.html", type="file", name="diagnosis/static/index.html",
         filePath="diagnosis/static/index.html", language="html",
         summary="Single-page application: vanilla JS DSM-5-TR criteria checklist UI. No build step. Exposes window.createDiagnosisModule({root, apiBaseUrl, embedded, initialCode}) returning {mount(), unmount(), setPatientCode()}. Derives all display from GET /diagnosis/_meta rules contract — JS never reimplements DSM logic. Stamps CSRF token from <meta name='csrf-token'> on every write.",
         tags=["spa","vanilla-js","embeddable","criteria-ui","no-build-step"], fileCategory="markup"),
    node(id="file:docs/api-contract.md", type="document", name="docs/api-contract.md",
         filePath="docs/api-contract.md", language="markdown",
         summary="Canonical REST API contract: route shapes, request/response bodies, error codes, auth, CSRF, route discovery, invariants. Locked against the live router by test_unittest.TestRestContract.test_api_contract_doc_lists_every_live_route. If the code and this document disagree, the code wins.",
         tags=["api-contract","canonical-spec","insight-integrator"], fileCategory="docs"),
    node(id="file:HANDOFF.md", type="document", name="HANDOFF.md",
         filePath="HANDOFF.md", language="markdown",
         summary="Deep-module handoff guide for future LLMs or humans. Maps the codebase architecture, design decisions, seam layout, env knobs, self-check chain, and the clinician-authority invariant.",
         tags=["handoff","architecture","design-decisions","llm-guide"], fileCategory="docs"),
    node(id="file:README.md", type="document", name="README.md",
         filePath="README.md", language="markdown",
         summary="User-facing module overview: DSM-5-TR schizophrenia criteria checklist for Insight. Interface table, CSRF protocol, patient identity, readiness probe, standalone and mounted deployment, embeddable UI contract.",
         tags=["readme","user-facing","overview"], fileCategory="docs"),
    node(id="file:requirements.txt", type="config", name="requirements.txt",
         filePath="requirements.txt", language="txt",
         summary="Python dependencies: fastapi>=0.110, uvicorn[standard]>=0.27, pydantic>=2.5, httpx2>=1.0, httpcore.",
         tags=["dependencies","python","fastapi","uvicorn"], fileCategory="config"),
    node(id="file:.understand-anything/.understandignore", type="config", name=".understand-anything/.understandignore",
         filePath=".understand-anything/.understandignore", language="unknown",
         summary="Understand-anything ignore patterns: excludes .venv, __pycache__, graphify-out, .understand-anything, *.db, diagnosis_store.db, notebooks, and scratch files.",
         tags=["understandignore","exclusions"], fileCategory="config"),
  ],
  "edges": [
    # Tests -> diagnosis modules (tested_by reversed to production -> test in merge)
    edge("file:test_unittest.py","file:diagnosis/criteria.py","imports",0.7),
    edge("file:test_unittest.py","file:diagnosis/api.py","imports",0.7),
    edge("file:test_unittest.py","file:diagnosis/store.py","imports",0.7),
    edge("file:test_unittest.py","file:diagnosis/patient.py","imports",0.7),
    edge("file:test_unittest.py","file:diagnosis/readiness.py","imports",0.7),
    edge("file:test_unittest.py","file:diagnosis/config.py","imports",0.7),
    edge("file:test_unittest.py","file:diagnosis/auth.py","imports",0.7),
    edge("file:test_unittest.py","file:diagnosis/csrf.py","imports",0.7),
    edge("file:test_auth.py","file:diagnosis/api.py","imports",0.7),
    edge("file:test_auth.py","file:diagnosis/auth.py","imports",0.7),
    edge("file:test_auth.py","file:diagnosis/deps.py","imports",0.7),
    edge("file:test_config.py","file:diagnosis/config.py","imports",0.7),
    edge("file:test_config.py","file:diagnosis/app.py","imports",0.7),
    edge("file:test_config.py","file:diagnosis/__main__.py","imports",0.7),
    edge("file:test_csrf.py","file:diagnosis/api.py","imports",0.7),
    edge("file:test_csrf.py","file:diagnosis/csrf.py","imports",0.7),
    edge("file:test_csrf.py","file:diagnosis/page.py","imports",0.7),
    edge("file:test_discovery.py","file:diagnosis/api.py","imports",0.7),
    edge("file:test_discovery.py","file:diagnosis/dashboard.py","imports",0.7),
    edge("file:test_embed.py","file:diagnosis/api.py","imports",0.7),
    edge("file:test_embed.py","file:diagnosis/page.py","imports",0.7),
    edge("file:test_patient.py","file:diagnosis/diagnosis_api.py","imports",0.7),
    edge("file:test_patient.py","file:diagnosis/patient.py","imports",0.7),
    edge("file:test_patient.py","file:diagnosis/auth.py","imports",0.7),
    edge("file:test_readiness.py","file:diagnosis/app.py","imports",0.7),
    edge("file:test_readiness.py","file:diagnosis/readiness.py","imports",0.7),
    edge("file:test_routes.py","file:diagnosis/api.py","imports",0.7),
    edge("file:test_routes.py","file:diagnosis/page.py","imports",0.7),
    edge("file:test_routes.py","file:diagnosis/dashboard.py","imports",0.7),
    edge("file:test_routes.py","file:diagnosis/diagnosis_api.py","imports",0.7),
    # HTML reads static content
    edge("file:diagnosis/static/index.html","file:diagnosis/static/index.html","contains",1.0),
    # Docs reference docs
    edge("file:docs/api-contract.md","file:README.md","documents",0.5),
    edge("file:HANDOFF.md","file:diagnosis/api.py","documents",0.5),
    edge("file:HANDOFF.md","file:diagnosis/criteria.py","documents",0.5),
    # Static HTML is served by page.py
    edge("file:diagnosis/page.py","file:diagnosis/static/index.html","serves",0.5),
    # Requirements documents dependencies
    edge("file:requirements.txt","file:diagnosis/app.py","documents",0.5),
  ]
}

# Write batch files
for i, b in enumerate([b1, b2, b3, b4, b5], 1):
    with open(f"{OUT}\\batch-{i}.json", "w", encoding="utf-8") as f:
        json.dump(b, f, indent=2)
    print(f"Written batch-{i}.json: {len(b['nodes'])} nodes, {len(b['edges'])} edges")

print("All 5 batch files written.")
print(f"Total nodes: {sum(len(b['nodes']) for b in [b1,b2,b3,b4,b5])}")
print(f"Total edges: {sum(len(b['edges']) for b in [b1,b2,b3,b4,b5])}")